DROP TABLE IF EXISTS MUJERES;

CREATE TABLE MUJERES(
  ID NUMBER NOT NULL PRIMARY KEY,
  NOMBRE_P VARCHAR(255) NOT NULL,
  URL VARCHAR(255) NOT NULL,
  PRECIO NUMBER NOT NULL
);

DROP TABLE IF EXISTS CARRITO;

CREATE TABLE CARRITO(
  ID NUMBER NOT NULL PRIMARY KEY,
  NOMBRE_P VARCHAR(255) NOT NULL,
  PRECIO NUMBER NOT NULL
);
